### ISSUE TITLE
Error Running Full Analysis:  Process `fastp (1_R1)` terminated with an error exit status (255)

### ISSUE THREAD

**Issue by andypaige772** [PalMuc/TransPi#41]
Hi, 

I have an issue with trying to run Full Analysis on TransPi. I have 8 files containing paired end data named 1_R1.fastq.gz, 1_R2.fastq.qz, etc that I would like to produce a de novo transcriptome from. 

I cloned the repository and ran the configuration using the bash precheck_TransPi.sh for the conda installation (option 1). Everything was downloaded and installed without any error. 

I tried to use the full analysis by running 
"nextflow run TransPi.nf -- all --reads .<path_to_reads>/*.fastq.gz --k 25,35,55,75,85 --maxReadLen 150 -profile conda"

I receive the following error message: 

Something went wrong. Check error message below and/or log files.
Error executing process > 'fastp (1_R1)'

Caused by:
  Process `fastp (1_R1)` terminated with an error exit status (255)

Command executed:

  fastp -i 1_R1.fastq.gz -I null -o left-1_R1.filter.fq -O right-1_R1.filter.fq --detect_adapter_for_pe                     --average_qual 5 --overrepresentation_analysis --html 1_R1.fastp.html --json 1_R1.fastp.json                     --thread 8 --report_title 1_R1

  v=$( fastp --version 2>&1 | awk '{print $2}' )
  echo "fastp: $v" >fastp.version.txt

Command exit status:
  255

Command output:
  (empty)

Command error:
  ERROR: Failed to open file: null

Work dir:
  /data/gn2311/transpi/TransPi/work/ae/ec5145900bb3af7866a1cb7e83f07f

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`

I also checked the command.sh file, which contains the following:

#!/bin/bash -ue
fastp -i 1_R1.fastq.gz -I null -o left-1_R1.filter.fq -O right-1_R1.filter.fq --detect_adapter_for_pe                     --average_qual 5 --overrepresentation_analysis --html 1_R1.fastp.html --json 1_R1.fastp.json                     --thread 8 --report_title 1_R1

v=$( fastp --version 2>&1 | awk '{print $2}' )
echo "fastp: $v" >fastp.version.txt

I am not sure what is causing the error, could you please let me know how to fix this issue?

Best,
Andy

**Comment by sivasubramanics** [comment]
Try to run it with read path within the quotes. .<path_to_reads>/*.fastq.gz to '.<path_to_reads>/*.fastq.gz'

**Comment by andypaige772** [comment]
Thank you for your response!

Running
`nextflow run TransPi.nf -- all --reads '.<path_to_reads>/*_R[1,2].fastq.gz' --k 25,35,55,75,85 --maxReadLen 150 -profile conda `
works. However, there is another error that pops up now when the pipeline reaches busco:

_**Error executing process > 'busco4_tri (1)'

Caused by:
  Process `busco4_tri (1)` terminated with an error exit status (1)

Command executed:

  echo -e "\n-- Starting BUSCO --\n"

  busco -i 1.Trinity.fa -o 2.Trinity.bus4 -l ./DBs/busco_db/diptera_odb10/ -m tran -c 8 --offline

  echo -e "\n-- DONE with BUSCO --\n"

  cp 1.Trinity.bus4/short_summary.*.1.Trinity.bus4.txt .
  cp 1.Trinity.bus4/run_*/full_table.tsv full_table_1.Trinity.bus4.tsv

Command exit status:
  1

Command output:

  -- Starting BUSCO --

  INFO: ***** Start a BUSCO v4.1.4 analysis, current time: 04/03/2022 17:39:55 *****
  INFO: Configuring BUSCO with /data/gn2311/transpi/TransPi/condaEnv/env-e8d22bfae5e32eac973114001910dada/share/busco/config.ini
  INFO: Mode is transcriptome
  INFO: Input file is 1.Trinity.fa

Command error:
  ERROR:        ./DBs/busco_db/diptera_odb10/ does not exist
  ERROR:        BUSCO analysis failed !
  ERROR:        Check the logs, read the user guide, and check the BUSCO issue board on https://gitlab.com/ezlab/busco/issues

Work dir:
  /data/gn2311/transpi/TransPi/work/2d/5eebdba2aff2e9d5ebf695f39da401

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`**_

However, the _ ./DBs/busco_db/diptera_odb10/_ does exist and nextflow should have access to it. I tried to to rerun the precheck_TransPi.sh script with different paths to busco but none of them work.

Could you please let me know what is causing the issue and how I could possibly resolve it? Thank you!

**Comment by sivasubramanics** [comment]
Check in your nextflow.config, if the DB path is provided correctly. In my case the mount point is linked to the Transpi, root path. Hence it worked well.

Eg:
busco4db="/home/name/src/TransPi/DBs/busco_db/viridiplantae_odb10"

**Comment by andypaige772** [comment]
I used the absolute path and it was able to continue the run. 

Then I ran into an issue with the RNAQUAST environment, but I was able to create the environment prior to resuming the run as suggested by the other github issue. 

I continued the run, but just received the following error message.  I can see that there may be an issue with the device saying there is not space, potentially because only one core is being used, if I understand correctly. Could you please let me know if you have any suggestions as to how I can resolve this issue. 

Error executing process > 'busco4_tri (1)'

Caused by:
  Process `busco4_tri (1)` terminated with an error exit status (120)

Command executed:

  echo -e "\n-- Starting BUSCO --\n"

  busco -i 1.Trinity.fa -o 1.Trinity.bus4 -l /data/gn2311/transpi/TransPi/DBs/busco_db/diptera_odb10/ -m tran -c 8 --offline

  echo -e "\n-- DONE with BUSCO --\n"

  cp 1.Trinity.bus4/short_summary.*.1.Trinity.bus4.txt .
  cp 1.Trinity.bus4/run_*/full_table.tsv full_table_1.Trinity.bus4.tsv

Command exit status:
  120

Command output:

  -- Starting BUSCO --

  INFO: ***** Start a BUSCO v4.1.4 analysis, current time: 04/07/2022 08:52:49 *****
  INFO: Configuring BUSCO with /data/gn2311/transpi/TransPi/condaEnv/env-e8d22bfae5e32eac973114001910dada/share/busco/config.ini
  INFO: Mode is transcriptome
  INFO: Input file is 1.Trinity.fa
  INFO: Using local lineages directory /data/gn2311/transpi/TransPi/DBs/busco_db/diptera_odb10/
  WARNING:      You are using BLAST version 2.12.0+. This is known to yield inconsistent results when multithreading. BLAST will run on a single core as a result. For performance improvement, please upgrade to BLAST 2.10.1+.
  INFO: Running BUSCO using lineage dataset  (eukaryota, 2020-08-05)
  INFO: Running 1 job(s) on makeblastdb, starting at 04/07/2022 08:52:53
  INFO: Creating BLAST database with input file
  INFO: [makeblastdb]   1 of 1 task(s) completed
  INFO: Running a BLAST search for BUSCOs against created database
  INFO: Running 1 job(s) on tblastn, starting at 04/07/2022 08:53:16

Command wrapper:
  INFO: Running a BLAST search for BUSCOs against created database
  INFO: Running 1 job(s) on tblastn, starting at 04/07/2022 08:53:16
  --- Logging error ---
  tee: .command.err: No space left on device
  Traceback (most recent call last):
    File "/data/gn2311/transpi/TransPi/condaEnv/env-e8d22bfae5e32eac973114001910dada/lib/python3.9/logging/__init__.py", line 1087, in emit
      self.flush()
    File "/data/gn2311/transpi/TransPi/condaEnv/env-e8d22bfae5e32eac973114001910dada/lib/python3.9/logging/__init__.py", line 1067, in flush
      self.stream.flush()
  OSError: [Errno 28] No space left on device
  Call stack:
    File "/data/gn2311/transpi/TransPi/condaEnv/env-e8d22bfae5e32eac973114001910dada/lib/python3.9/threading.py", line 930, in _bootstrap
      self._bootstrap_inner()
    File "/data/gn2311/transpi/TransPi/condaEnv/env-e8d22bfae5e32eac973114001910dada/lib/python3.9/threading.py", line 973, in _bootstrap_inner
      self.run()
    File "/data/gn2311/transpi/TransPi/condaEnv/env-e8d22bfae5e32eac973114001910dada/lib/python3.9/threading.py", line 910, in run
      self._target(*self._args, **self._kwargs)
    File "/data/gn2311/transpi/TransPi/condaEnv/env-e8d22bfae5e32eac973114001910dada/lib/python3.9/site-packages/busco/BuscoLogger.py", line 200, in _flusher
      self.write(data.decode())
    File "/data/gn2311/transpi/TransPi/condaEnv/env-e8d22bfae5e32eac973114001910dada/lib/python3.9/site-packages/busco/BuscoLogger.py", line 205, in write
      return self.logger.log(self.level, data)
  Message: "terminate called after throwing an instance of 'std::__ios_failure'"
  Arguments: ()
  --- Logging error ---
  Traceback (most recent call last):
    File "/data/gn2311/transpi/TransPi/condaEnv/env-e8d22bfae5e32eac973114001910dada/lib/python3.9/logging/__init__.py", line 1087, in emit
      self.flush()
    File "/data/gn2311/transpi/TransPi/condaEnv/env-e8d22bfae5e32eac973114001910dada/lib/python3.9/logging/__init__.py", line 1067, in flush
      self.stream.flush()
  OSError: [Errno 28] No space left on device
  Call stack:
    File "/data/gn2311/transpi/TransPi/condaEnv/env-e8d22bfae5e32eac973114001910dada/lib/python3.9/threading.py", line 930, in _bootstrap
      self._bootstrap_inner()
    File "/data/gn2311/transpi/TransPi/condaEnv/env-e8d22bfae5e32eac973114001910dada/lib/python3.9/threading.py", line 973, in _bootstrap_inner
      self.run()
    File "/data/gn2311/transpi/TransPi/condaEnv/env-e8d22bfae5e32eac973114001910dada/lib/python3.9/threading.py", line 910, in run
      self._target(*self._args, **self._kwargs)
    File "/data/gn2311/transpi/TransPi/condaEnv/env-e8d22bfae5e32eac973114001910dada/lib/python3.9/site-packages/busco/BuscoLogger.py", line 200, in _flusher
      self.write(data.decode())
    File "/data/gn2311/transpi/TransPi/condaEnv/env-e8d22bfae5e32eac973114001910dada/lib/python3.9/site-packages/busco/BuscoLogger.py", line 205, in write
      return self.logger.log(self.level, data)
  Message: '  what():  basic_ios::clear: iostream error'
  Arguments: ()
  CRITICAL:     Unhandled exception occurred:
  multiprocessing.pool.RemoteTraceback:
  """
  Traceback (most recent call last):
    File "/data/gn2311/transpi/TransPi/condaEnv/env-e8d22bfae5e32eac973114001910dada/lib/python3.9/logging/__init__.py", line 1157, in close
      self.flush()
    File "/data/gn2311/transpi

Work dir:
  /data/gn2311/transpi/TransPi/work/61/9248d9dc616bcae53fae1d41c23d34
Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`


#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGBUS (0x7) at pc=0x00007f48eb134d45, pid=15518, tid=0x00007f4771ede700
#
# JRE version: OpenJDK Runtime Environment (8.0_212-b03) (build 1.8.0_212-8u212-b03-0ubuntu1.18.04.1-b03)
# Java VM: OpenJDK 64-Bit Server VM (25.212-b03 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [libc.so.6+0x18ed45]
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /data/gn2311/transpi/TransPi/hs_err_pid15518.log
Segmentation fault (core dumped)

**Comment by andypaige772** [comment]
The previous busco4 error was resolved after resuming the run again. I have since received an error regarding the diamon_blastx. I have tried to resume it multiple times, but continue to get the same error. Would you have any idea how to resolve the issue? Thank you again for your help.

Error executing process > 'swiss_diamond_trinotate (2)'

Caused by:
  Missing output file(s) `2.diamond_blastx.outfmt6` expected by process `swiss_diamond_trinotate (2)`

Command executed:

  dbPATH=/data/gn2311/transpi/TransPi/DBs/sqlite_db/
  echo -e "\n-- Starting Diamond --\n"
  if [ ! -d ${dbPATH} ];then
      echo "Directory ${dbPATH} not found. Run the precheck to fix this issue"
      exit 0
  elif [ -d ${dbPATH} ];then
      if [ ! -e ${dbPATH}/uniprot_sprot.pep ];then
          echo "File ${dbPATH}/uniprot_sprot.pep not found. Run the precheck to fix this issue"
          exit 0
      elif [ -e ${dbPATH}/uniprot_sprot.pep ];then
          if [ ! -e ${dbPATH}/uniprot_sprot.pep.dmnd ];then
              cp ${dbPATH}/uniprot_sprot.pep .
              diamond makedb --in uniprot_sprot.pep -d uniprot_sprot.pep -p 10
              echo -e "\n-- Starting with Diamond (blastx) --\n"
              diamond blastx -d uniprot_sprot.pep.dmnd -q 2_assembly.fasta -p 10 -f 6 -k 1 -e 0.001 >2.diamond_blastx.outfmt6
              echo -e "\n-- Done with Diamond (blastx) --\n"
              echo -e "\n-- Starting with Diamond (blastp) --\n"
              diamond blastp -d uniprot_sprot.pep.dmnd -q 2.combined.okay.fa.transdecoder.pep -p 10 -f 6 -k 1 -e 0.001 >2.diamond_blastp.outfmt6
              echo -e "\n-- Done with Diamond (blastp)  --\n"
          elif [ -e ${dbPATH}/uniprot_sprot.pep.dmnd ];then
              cp ${dbPATH}/uniprot_sprot.pep.dmnd .
              echo -e "\n-- Starting with Diamond (blastx) --\n"
              diamond blastx -d uniprot_sprot.pep.dmnd -q 2_assembly.fasta -p 10 -f 6 -k 1 -e 0.001 >2.diamond_blastx.outfmt6
              echo -e "\n-- Done with Diamond (blastx) --\n"
              echo -e "\n-- Starting with Diamond (blastp) --\n"
              diamond blastp -d uniprot_sprot.pep.dmnd -q 2.combined.okay.fa.transdecoder.pep -p 10 -f 6 -k 1 -e 0.001 >2.diamond_blastp.outfmt6
              echo -e "\n-- Done with Diamond (blastp)  --\n"
          fi
      fi
  fi
  echo -e "\n-- Done with Diamond --\n"

  v=$( diamond --version 2>&1 | tail -n 1 | cut -f 3 -d " " )
  echo "Diamond: $v" >diamond.version.txt

Command exit status:
  0
Command output:

  -- Starting Diamond --

  File /data/gn2311/transpi/TransPi/DBs/sqlite_db//uniprot_sprot.pep not found. Run the precheck to fix this issue

Work dir:
  /data/gn2311/transpi/TransPi/work/07/99367474327db86639d8a03b6d40f6

Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line
